# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SunXp_Inke' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SunXp_Inke

  target 'SunXp_InkeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SunXp_InkeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'AFNetworking', '~> 3.2.0'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYKit', '~> 1.0.9'

end
